# general
run_name: 'test' #'augmented_version'
seed: 0 # run seed

# channel
channel_type: 'SISO' # Channel type values: ['SISO','MIMO'].
channel_model: 'Synthetic' # Physical channel models: ['Cost2100','Synthetic']
detector_type: 'black_box' # 'model' or 'black_box'
linear: True # channel linearity. Boolean value.
fading_in_channel: True # If the channel is fading/non-fading. values: [True, False]
modulation_type: 'BPSK' # ['BPSK','QPSK']

# sampler
aug_type: [ ] # ['geometric_augmenter','translation_augmenter','rotation_augmenter']
online_repeats_n: 1 # number of desired augmented words out of online_total_words. values: 0<=online_repeats_n<=online_total_words

# validation hyperparameters
val_block_length: 10600 # coherence block time, total size of pilot + data. values: int.
pilot_size: 600 # pilot bits
blocks_num: 25 # number of validation frames. values: int.
val_snr: 12 # start SNR value. values: float.
eval_mode: 'by_word' # Type of evaluation per block - 'by_word'.

# online training hyperparameters
is_online_training: True # Whether to run the online training (as in ViterbiNet). values: [True, False].
loss_type: 'CrossEntropy' # Loss type. values: 'BCE','CrossEntropy','MSE'.
optimizer_type: 'Adam' # Optimizer type. values: 'Adam','RMSprop','SGD'.
from_scratch: False