# general
run_name: 'test' # the name of the experiment
seed: 0 # run seed

# channel
channel_type: 'MIMO' # Channel type values: ['SISO','MIMO'].
channel_model: 'Synthetic' # Physical channel models: ['Cost2100','Synthetic']
detector_type: 'bayesian_black_box'
# 'seq_model' or 'end_to_end_model' or 'model_based_bayesian' or 'bayesian' or 'black_box' or 'bayesian_black_box'
linear: True # channel linearity. Boolean value.
fading_in_channel: False # If the channel is fading/non-fading. values: [True, False]
snr: 12 # validation SNR value. values: float.
modulation_type: 'QPSK' # ['BPSK','QPSK','EightPSK']

# protocol
block_length: 12900 # coherence block time, total size of pilot + data. values: int.
pilot_size: 900 # pilot bits
blocks_num: 10 # number of validation frames. values: int.

# online training hyperparameters
is_online_training: True # Whether to run the online training (as in ViterbiNet). values: [True, False].
loss_type: 'CrossEntropy' # Loss type. values: 'BCE','CrossEntropy','MSE'.
optimizer_type: 'Adam' # Optimizer type. values: 'Adam','RMSprop','SGD'.